#!/usr/bin/env bash
# Dynamically discover coding-agent CLIs and write _/coding-agents.{md,json}
set -euo pipefail
OUT_DIR="${1:-_}"
PROJECT_ROOT="${2:-$(pwd)}"
cd "$PROJECT_ROOT"
mkdir -p "$OUT_DIR"

have() { command -v "$1" >/dev/null 2>&1; }

TS="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
HOST="unknown"
if [[ -n "${GROK_SESSION_ID:-}" ]] || pgrep -f '[g]rok' >/dev/null 2>&1; then HOST="grok"
elif [[ -n "${CLAUDECODE:-}${CLAUDE_CODE_ENTRYPOINT:-}" ]]; then HOST="claude"
elif [[ -n "${CODEX_HOME:-}" ]]; then HOST="codex"
elif [[ -n "${CURSOR_TRACE_ID:-}" ]]; then HOST="cursor"
fi

declare -a IDS=() FAMS=() BINS=() PATHS=() VERS=() HEADLESS=() CODE=()

add_agent() {
  local id="$1" fam="$2" bin="$3" hl="$4" code="$5"
  have "$bin" || return 0
  local p ver
  p="$(command -v "$bin")"
  ver="$("$bin" --version 2>/dev/null | head -n1 || true)"
  IDS+=("$id"); FAMS+=("$fam"); BINS+=("$bin"); PATHS+=("$p"); VERS+=("$ver")
  HEADLESS+=("$hl"); CODE+=("$code")
}

add_agent grok     grok     grok     'grok -p "{prompt}"'                'grok -p "{prompt}"'
add_agent claude   claude   claude   'claude -p --bare "{prompt}"'       'claude -p --bare "{prompt}"'
add_agent codex    codex    codex    'codex exec "{prompt}"'             'codex review'
add_agent copilot  copilot  copilot  'copilot -p "{prompt}"'             'copilot -p "{prompt}"'
add_agent gemini   gemini   gemini   'gemini -p "{prompt}"'              'gemini -p "{prompt}"'
add_agent aider    aider    aider    'aider --yes --message "{prompt}"'  'aider --yes --message "{prompt}"'
add_agent cursor   cursor   cursor-agent 'cursor-agent -p "{prompt}"'    'cursor-agent -p "{prompt}"'
add_agent opencode opencode opencode 'opencode run "{prompt}"'           'opencode run "{prompt}"'
add_agent amp      amp      amp      'amp -p "{prompt}"'                 'amp -p "{prompt}"'
add_agent qwen     qwen     qwen     'qwen -p "{prompt}"'                'qwen -p "{prompt}"'

if [[ ${#IDS[@]} -eq 0 ]] || ! printf '%s\n' "${IDS[@]}" | grep -qx copilot; then
  if have gh && gh extension list 2>/dev/null | grep -qi copilot; then
    IDS+=(copilot); FAMS+=(copilot); BINS+=(gh)
    PATHS+=("$(command -v gh)"); VERS+=("$(gh --version 2>/dev/null | head -n1 || true)")
    HEADLESS+=('gh copilot suggest -t shell "{prompt}"'); CODE+=('gh copilot explain')
  fi
fi

PEERS=()
for i in "${!IDS[@]}"; do
  [[ "${FAMS[$i]}" == "$HOST" ]] && continue
  PEERS+=("${IDS[$i]}")
done

# JSON (minimal, no jq required)
{
  echo "{"
  echo "  \"discovered_at\": \"$TS\","
  echo "  \"host_family\": \"$HOST\","
  echo "  \"project_root\": \"$PROJECT_ROOT\","
  echo "  \"judge_peers\": [$(printf '"%s",' "${PEERS[@]}" | sed 's/,$//')],"
  echo "  \"agents\": ["
  for i in "${!IDS[@]}"; do
    comma=","; [[ $i -eq $((${#IDS[@]}-1)) ]] && comma=""
    ver_esc="${VERS[$i]//\"/\\\"}"
    hl_esc="${HEADLESS[$i]//\"/\\\"}"
    code_esc="${CODE[$i]//\"/\\\"}"
    path_esc="${PATHS[$i]//\\/\\\\}"
    cat <<EOF
    {
      "id": "${IDS[$i]}",
      "family": "${FAMS[$i]}",
      "binary": "${BINS[$i]}",
      "path": "$path_esc",
      "version": "$ver_esc",
      "headless": "$hl_esc",
      "code_review": "$code_esc",
      "available": true
    }$comma
EOF
  done
  echo "  ]"
  echo "}"
} > "$OUT_DIR/coding-agents.json"

{
  echo "# Coding agents inventory"
  echo ""
  echo "Auto-generated by \`scripts/discover-coding-agents.sh\` (or \`/kosmo-sdlc:discover-agents\`)."
  echo "Used by **ai-judge** for multi-CLI peer selection."
  echo ""
  echo "- **discovered_at:** $TS"
  echo "- **host_family:** \`$HOST\`"
  if [[ ${#PEERS[@]} -gt 0 ]]; then
    echo -n "- **judge_peers (exclude host):** "
    printf '`%s` ' "${PEERS[@]}"
    echo ""
  else
    echo "- **judge_peers (exclude host):** _none — install another CLI_"
  fi
  echo ""
  echo "## Available agents"
  echo ""
  echo "| id | family | binary | version | headless |"
  echo "| --- | --- | --- | --- | --- |"
  for i in "${!IDS[@]}"; do
    echo "| \`${IDS[$i]}\` | \`${FAMS[$i]}\` | \`${BINS[$i]}\` | ${VERS[$i]:—} | \`${HEADLESS[$i]}\` |"
  done
  echo ""
  echo "## Judge policy"
  echo ""
  echo "1. Prefer peers whose \`family\` ≠ \`host_family\`."
  echo "2. Need ≥2 peers for multi-judge; else warn."
  echo "3. Re-run: \`/kosmo-sdlc:discover-agents\`."
  echo ""
  echo "## Machine paths"
  echo ""
  for i in "${!IDS[@]}"; do
    echo "- **${IDS[$i]}:** \`${PATHS[$i]}\`"
  done
  echo ""
} > "$OUT_DIR/coding-agents.md"

echo "Wrote $OUT_DIR/coding-agents.md"
echo "Wrote $OUT_DIR/coding-agents.json"
echo "host_family=$HOST peers=${PEERS[*]:-}"
